### ISSUE TITLE
ブログメニュープレビューの不具合

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#15]
7.0.0betaのバグ報告です。
ブログのメニュー編集で、編集後のプレビューを行うと、ブログのメニューが表示されずに、トップページのメニューが表示されます。ブログメニューの更新は正常にできます。ブログメニューのプレビューができない障害です。

**Comment by umihoshi** [comment]
beta2でもブログメニューのプレビューができないのは相変わらずです。

**Comment by umihoshi** [comment]
ver.7.0.2でも同じ症状です。

**Comment by big2men** [comment]
#75 で解決済み。
