### ISSUE TITLE
グーグルマップ表示エラー

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#19]
haikのバグ報告です。
Googleの仕様変更（APIキー導入）にHAIKが対応していないので、gmapが動作しません。googleの仕様変更以後のドメインで発生する障害です。HAIKの対応が必要です。
Forumでの調査結果は、
「htmlで貼り付けてOKの人とNGが出る人との環境の差は、GoogleのURLの問題というのがわかりました。
HAIKに最初から埋め込まれているﾏｯﾌﾟJavaの指定URLが問題で、ｈｔｍｌでjavaを埋め込むと、URLどうしが干渉してしまう事があり、エラーが出ていました。
干渉の有無はHPの構成やらなんやらに左右されるみたいです。」
ということです。
　CLUBの方ではhtmlの埋め込みでしのいでいますが、これではHAIKの利便性が損なわれるので、ぜひ以前のように、プラグインで簡単にマップが表示できる機能を復活していただきたい。htmlを知らなくても使えるのがHAIKの売りなのですから。

**Comment by umihoshi** [comment]
この問題はAPIキーでは解決できなかったので、HAIKJ側の問題と思います。

**Comment by big2men** [comment]
なるほど、把握しました。
新規ドメインではAPIキーが無いとエラーになるんですね！

これは API キーを埋め込められるようにすれば問題ないのですが、QHMの設定項目を増やす必要があります。
昔あった設定項目を復活させるか。。。

**Comment by umihoshi** [comment]
＞HAIKに最初から埋め込まれているﾏｯﾌﾟJavaの指定URLが問題で、ｈｔｍｌでjavaを埋め込むと、URLどうしが干渉＞してしまう事があり、エラーが出ていました。

　HAIKでキーを埋め込む設定ができればユーザーにもわかりやすいですが、
　上記にあるキーを埋め込んでもエラーになるというこの事例はHAIK自体の問題でしょう。

**Comment by umihoshi** [comment]
forumの検証では、キーを設置してもエラーになる事例があり、

＞HAIKに最初から埋め込まれているﾏｯﾌﾟJavaの指定URLが問題で、ｈｔｍｌでjavaを埋め込むと、URLどうしが干渉してしまう事があり、エラーが出ていました。

　ここが問題点のようです。HAIK内のJAVAを修正する必要があるということでしょうか。

**Comment by big2men** [comment]
@umihoshi
未確認ですが、おそらくそうだと思います。
#gmap が出力する Google マップの JavaScript 読み込みタグと、 `#beforescript` 等で書き込んだ読み込みタグがあるからですね。

[こちら](https://developers.google.com/maps/documentation/javascript/get-api-key?hl=ja)にある、これを直接 gmap プラグインに書いたらエラーは出なくなるかもです。（未確認です）

```
<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>
```

↑を[ここ](https://github.com/open-qhm/qhm/blob/master/plugin/gmap.inc.php#L106)に書くイメージです。

ちなみに、 JAVA と表記すると別のプログラミング言語となるので js あるいは JavaScript と表記してください 💻
