### ISSUE TITLE
#article プラグインで任意のJavaScriptコードが実行される危険性

### ISSUE THREAD

**Issue by ishimaru130** [open-qhm/qhm#22]
#articleプラグインで掲示板を設置した場合、メッセージ内容に#htmlプラグインを大文字で
記述した場合に、lib/func.phpのwikiescapeでは小文字の#htmlで始まる行しか
文字パターンにマッチせずに、JavaScriptを記述した場合に実行されてしまう危険性がある。

lib/func.php の function wikiescape 内の
$ret .= preg_replace('/^#html/', "# html", $line) ."\n";
を
$ret .= preg_replace('/^(#)(html|beforescript|style|lastscript)/i', "$1 $2", $line) ."\n";
とすると回避出来るようです。

**Comment by umihoshi** [comment]
HAIKーCLUBの皆さんにも警告を出して該当の「おなじない」の使用を中止するように呼びかけることと、サイト汚染の点検ができる方法を提示すべきです。この機会に脆弱性の総点検と対処をされることを望みます。

**Comment by umihoshi** [comment]
（FRUMｋから引用。）

注意したほうがいいというレベルではありません。
重大なXSS脆弱性です。

たとえば、これが投稿できてしまいます。
#HTML{{
<script>
alert(document.cookie);
</script>
}}

ログインした状態で閲覧すればわかりますが 'QHMSSID5' （管理者を識別するためのCookie）が含まれています。
alertで表示するだけなら実害はありませんが、実際はいくらでも悪用可能です。
QHMSSID5の情報を盗んでしまえば、管理者になりすましてログインできます。
（掲示板に攻撃JavaScriptを貼る→管理者がログインしたまま掲示板に来るのを待つ→罠に掛かったら管理者になりすましてコンテンツ書き換え放題）

はっきり言って呆れるような脆弱性です。
セッションハイジャック可能なまま4年も放置されているCMSは初めて見ました。

（引用終わり。）

**Comment by tanakakc** [comment]
@ishimaru130 @umihoshi 

ご報告ありがとうございます。
本日中に、この脆弱性について修正をして、公開させていただきます。

**Comment by tanakakc** [comment]
@ishimaru130 @umihoshi 

さきほど、v6.0.5として修正版をリリースさせていただきました。
