### ISSUE TITLE
swfuの脆弱性も確認してください

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#25]
http://jvndb.jvn.jp/ja/contents/2012/JVNDB-2012-006025.html
に情報があります。
ベンダーの最新版を使うなど、安全に配慮した対処をお願いします。
私も念のためウイルスチェックをしたところ、

/public_html/swfu/js
と
public_html/swfu/d
に
　Tary.php
が検知され削除さしました。
確認をお願いします。

**Comment by umihoshi** [comment]
https://sourceforge.net/projects/swfupload.mirror/
でLast Update:のファイルをを取ってきて入れ替えてみました。動作は問題なしです。
これでver.2.5.0.beta3.2になります。
脆弱性はSWFUpload 2.2.0.1 およびそれ以前なので，対処できたのでしょうか？

**Comment by tanakakc** [comment]
@umihoshi 

ご報告ありがとうございます。
さきほど、v6.0.5として修正版をリリースいたしました。
