### ISSUE TITLE
dlexec.phpの脆弱性

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#27]
以下の脆弱性の指摘がありましたので、報告しておきます。未確認です。

(以下引用)
plugin/dlexec.phpにはサーバー上の好きなファイルをダウンロードできる脆弱性がある

**Comment by umihoshi** [comment]
確認できたそうです。以下いしまるさんのコメント。

ページ内に記述する・しないに関係なく、パスワードやデータファイルがダウンロード、閲覧できる重大な不具合です。放置して詳しい人が悪用すると大事なデータが漏洩します。
直ぐに対応したほうが良い内容です。

**Comment by ishimaru130** [comment]
フォーラムで最初に指摘されたevil hacker氏はかなり詳しい人だと思われます。
関連のプログラムは2011年からあるようですが、2チャンネルのようなサイトで
悪用の方法が出ていない事を願っています。脆弱性については、ネットで検索したり
情報があつまる他のサイトを時々調べたほうが良さそうですね。

**Comment by big2men** [comment]
はじめまして。以前QHMの開発をしていたものです。
脆弱性についてはユーザーやIPA、セキュリティ調査会社から指摘を受けたものは順次修正しておりましたが、これは初めての指摘です。

以前、 dlexec については、サーバー内のQHM（PHP）がアクセス可能なファイルであればダウンロードできる、という脆弱性があったのでソース・ファイルにファイルパスがないものはダウンロードできない、という修正は施しておりました。

しかし、ユーザーが投稿した `&dllink` から、というのは想定外でした。目からウロコです。
情報いただきありがとうございます。

これは緊急性の高い脆弱性ですので早急な対応が必要だと思います。
ですので、ここで、新仕様について議論もしておいた方が良いかと思います。


## 新仕様について

私としては、
「ソース・ファイルにファイルパスがないものはダウンロードできない」という前提で、さらに

* (A) 設置したQHMのディレクトリ（フォルダ）からみて `swfu/d` 以下のファイルのみ許可
* (B) 設置したQHMのディレクトリ以下のファイルのみ許可
* (C) コメントで `&dllink` `&dlbutton` を禁止する
* (D) `&dllink` を廃止し、 `#dllink` にする

のいずれかの制約を増やすのが良いかと思います。

### (A) 案について

挙げた中ではかなり厳しい制約となりますが、本脆弱性への対処としては最大限のセキュリティを考慮したものになります。

### (B) 案について

これは `/etc/passwd` といったファイルへのアクセスは防げますが、 `qhm.ini.php` や commu をインストールしたディレクトリのファイルをダウンロードできる危険性が依然存在します。
セキュリティ確保のため、設定ファイルで許可するディレクトリを指定できるようにする、といった追加仕様が必要となりそうです。
例： `files` ディレクトリのみ許可する→ `QHMインストールディレクトリ/files/` 以下のファイルのみダウンロード可能

### (C) 案について

これは既に存在する `&dllink` には対応できませんが、将来発生することを防ぐことができます。これ単体で行う、というよりは (A) や (B) との合わせ技にする、という方が良さそうです。
そもそもコメント投稿者が `&dllink` を投稿できること自体が不自然ですので。。。

### (D) 案について

これはちょっと強引ですが、コメント欄では使えなくなります。
ただし、既存のものが動かなくなるため、互換性を考えたら難しい対策です。
これを採用することはないと思いますが、可能性として書いておきます。

----

@umihoshi @ishimaru130 
HAIK CMS のページで実験していたようですが、該当部分はページごと消えていますね。報告されたのでしょうか？
身内じゃなければコメント欄に貼り付けるのはやりすぎかと思います。脆弱性を利用した不法アクセスにとられかねないので。。
今後は実験はご自身のサイトでお願いいたします。

では、長文失礼いたしました。
いつもQHMをご利用いただき、ありがとうございますm(_ _)m

**Comment by umihoshi** [comment]
問題の実験は最初にこの件をコメントされたevil hackerさんが「HAIKサイトでこんなことができる」という例で書かれた実験方法でしたが、forum管理人さんが、危険な書き込みとして該当部分を削除しました。
　haikでダウンロードサイトを運営しているユーザーでは、このプラグインを削除するというわけにも行かないでしょうから、当面は該当プラグインを別のわからない名前に変えてしまえば、勝手に使われることは防げるかもしれません。

**Comment by big2men** [comment]
> 当面は該当プラグインを別のわからない名前に変えてしまえば、勝手に使われることは防げるかもしれません。

この対応ではプラグイン名がバレたら意味ないので。。。
ここの議論はオープンになっていますしね。
互換性の点においてもアウトかと。

実際に利用したことがある方がいれば伺いたいです。
ダウンロードファイルはどこに置くことが多いんでしょうか。
うろ覚えですが、北研のマニュアルだとQHMディレクトリの下に専用のディレクトリを作っていたような。。。

**Comment by umihoshi** [comment]
>実際に利用したことがある方がいれば伺いたいです。
ダウンロードファイルはどこに置くことが多いんでしょうか。

　私はこのプラグインは使ってないので分かりませんが、tomzoさんの運営しているhaik forumの方には使った方のコメントがあったので、そちらで問いかけてはどうでしょう。こちらに書き込む人はごく限られていますから。といってもforumの方も不具合で定期的にデータが消えるということで、現在引っ越しの準備中です。来週には新しい掲示板に移動すると思いますが、書き込みは今でもできるので、そちらで聞く方が反応があると思います。

**Comment by Yujiro01** [comment]
ダウンロードしてもらうファイルの置き場所は任意です。

ファイル置き場とするディレクトリの名前を固定し、
そこ以外からはダウンロードできなくするのが早いかもです。

**Comment by tanakakc** [comment]
@umihoshi @ishimaru130 いつも、ご報告ありがとうございます。
@big2men 新仕様の提案ありがとうございます！

B案 + C案でよいのでは？と思います。
そして、管理者がディレクトリを指定できるようにすると良いと思います。

QHMのマニュアルサイトでは、`pub`ディレクトリを作成する例が出ていましたので、
デフォルトの許可ディレクトリを `pub` にしておくと、更新後も多くのユーザーの手間が省けるかもしれません。

**Comment by big2men** [comment]
@Yujiro01 @tanakakc 
お返事ありがとうございます。

そうですね、やはり (B) 案が良いですかね。
マニュアルで書いていたならデフォルト値は `pub` で良さそうですね。

## 許可ディレクトリについて

もう少し突っ込んで聞きたいのが、 (B) 案で `pub` 以外のディレクトリを指定したい時に、
設定内容を触れるとして、

* i) QHM のインストールディレクトリ以下のディレクトリのみ許可するのか
* ii) あるいは、どこでも許可するのか

というところです。
セキュリティの面でいえば、 (i) の方が高いですが、サイト管理者の立場で言えば、 (ii) の方が融通が効くものになっています。

例えば、用心深い人であれば、
ダウンロードさせるファイルは会員しかダウンロードできないようにしたい、万が一にでもファイル名がばれてダウンロードされたくない、と考えるかも知れません。

そこでWebサーバーの公開ディレクトリではない場所へファイルを置き、 `dlexec` を通してダウンロードをしてもらう、という方法を取りたいとします。
Xserver で例えると、 `ドメイン名/public_html` が公開ディレクトリです。この人は `ドメイン名/files` というディレクトリを作り、そこに置きたい、とします。

ですが、新仕様で「設置したQHMのディレクトリ以下のファイルのみ許可」としてしまうと、この場所に置けなくなり、仕方なく公開ディレクトリ以下に置くしかなくなります。


----

私は当初の提案通り (i) が良いと考えています。
QHMのインストールディレクトリより上位ディレクトリを許可すると、万が一QHMに管理者ログインされてしまった場合に、重要なファイルを盗られかねません。

```
管理者ログイン
→設定画面へ行く
→ダウンロード許可指定ディレクトリの変更（例： /etc ）
→ dllink をページに貼り付ける
→任意のファイルダウンロード（例： /etc/passwd ）
```

この脅威は限定しておくべきかと思います。

あ、限定したとして、上記のシナリオで改ざんがあった場合、HAIK-CMS での実験のように commu のファイルを盗るのは防げませんね（下層ディレクトリにあるので） 😅 
設定画面で変更できないようにすればいいかも知れないですね。分かる人はFTPやSSH経由で変更できる、的な。

**Comment by ishimaru130** [comment]
加えて対象となるファイルの拡張子を指定しなければならないようにしておくのが
良いと思います。
pdf, jpg, jpeg, gif, png , doc, docx, xls, xlxs, zip ,gz などがあれば通常は用が足りそうですが、
他にはどのようなものがあるのでしょうか。

**Comment by umihoshi** [comment]
フォルダを限定するよりも、ダウンロードできるファイルを個別指定することはできないのでしょうか。
プラグインのオプションで指定したファイルしかダウインローできないような仕様はどうでしょうか。
あるいはHAIKの設定で「ダウンロード許可ファイル」を指定するとかもどうでしょう。
安全のためには互換性を犠牲にするのもやむを得ないと思います。

**Comment by big2men** [comment]
@ishimaru130 
> 加えて対象となるファイルの拡張子を指定

良いですね 😄 かなりリスクを減らせられるかと。
後は音声やビデオ等のメディアファイルがあれば問題なさそうです。
もしそれ以外のファイルでも zip 圧縮すれば配布できますね。

@umihoshi 
うーん、ファイルを指定するのとディレクトリを指定するのではセキュリティ面ではあまり違いがないですね。
それよりも利便性が下がりすぎて誰も使わなくなってしまうのでは、と思います 😅 

結局、設定画面で許可ファイルが指定できるのであれば、管理画面に入られたらやりたい放題なわけです。
たとえ、管理画面に入られてもインストールディレクトリ以下にしか被害が及ばないように、というのが今まで提案していたものです。

> 2.プラグインのオプションで指定したファイルしかダウインローできないような仕様はどうでしょうか。

これは今でも施されております。
`&dllink(path/to/file,...){ダウンロード};`
と書いたら `paty/to/file` しかダウンロードできないようにしています。
ですが、コメント欄とかに書けるのでほとんど意味がない、というのが今回の顛末です。

なので、落とし所としては、
デフォルト許可ディレクトリ（  `swfu/d` `pub` あたり）と許可拡張子を決めつつ、

> 3.あるいはHAIKの設定で「ダウンロード許可ファイル」を指定する

こうなるわけです。
管理者しか利用できない設定画面でインストールディレクトリ以下のディレクトリを「ダウンロード許可」するようにすれば、安全を確保しつつ、利便性もそこまで損なわないのではないでしょうか？

**Comment by tanakakc** [comment]
@big2men @umihoshi @ishimaru130 @Yujiro01 

では、
* ダウンロード許可ディレクトリの限定（ `swfu/d` or `pub` ）
* 設定画面にて許可ディレクトリの変更ができる（QHMディレクトリ以下のみ）
* ダウンロード可能なファイル拡張子の設定ができる

という仕様で決定にしようと思います。

ご意見ありがとうございました。
とても助かりました。

**Comment by umihoshi** [comment]
この問題もbeta2で解決したのでしょうか？

**Comment by big2men** [comment]
@umihoshi こちらも #36 で対応中です。
