### ISSUE TITLE
APIキーを設置しても#gmapと#gmapfunがエラーになる。

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#29]
GoogleMapから緯度経度を取得しても，#gmapのオプション指定では，緯度経度の順序が反対になり，貼り付けが煩わしい。以前のプラグインでは正しい順序だったのでなぜ改訂版で反対になったのか理解に苦しむ。Googleと同じ順番に戻してほしい。

**Comment by umihoshi** [comment]
これ本当に不便です。GoogleMapから緯度経度をコピーしてそのまま貼り付けられないです。いちいち逆にしければならない手間です。

**Comment by big2men** [comment]
これ難しい問題ですね 😱 
後方互換を考えると引数の順番は変えられないので。。
確かに不便なのでなんか考えてみましょう。

キーワード引数を追加仕様とすることで順番は保持できるかもしれません。
記述を追加してもらう必要がありますが。。
こんな風に。

```
#gmap{{
,どこどこ,,lat=34.827338,lng=135.592382
}}
```

@umihoshi 
緯度経度を使うのはジオコーディングがうまくいかない時と考えられますが、 基本的に緯度経度を使う方針ということですか？

**Comment by umihoshi** [comment]
#gmapfunの時は問題なかったのでhaikになってプラグインが変わったことによる逆転です。
最初プラグインを入れ替えたら違う場所が表示されたので，気がつきました。互換性はこのとき失われています。
#gmapfunをそのまま使えばいいのでしょうけど，HAIKからはりつけると#gmapですからねえ。
何でわざわざGoogleと逆にしたのかと思いましたよ。GoogleMapプラグインなのにね。

市街地ばかりで使っていれば住所で問題ないでしょうね。
私の場合は緯度経度を使うのは，観測地データなどで住所の無い辺境も多いことが要因です。Mapで位置を探して緯度経度を取得すれば簡単ですので。

**Comment by umihoshi** [comment]
別の案としては、このプラグインの互換性が問題なら、旧版の#gmapfunを#gmapfun2に名前を変えて修正版をリリースするのもいいのではないでしょうか。

**Comment by umihoshi** [comment]
そもそも#gmapfunと#gmapの互換性が無くなった事がトラブルの原因ですから、#gmapfun2を作って貰えれば、サイトの書き直しも最小限で済みます。この件はマニュアルにも無くて、原因特定に悩みました。緯度経度を逆にしたならマニュアルでそう書いて欲しいですね。
　#gmapの不具合のとき、原因をtomzoさんに教えてもらっで苦労してして緯度経度を書き換えたのを、再度元に戻すよりはいくらいかましでしょう。新プラグインでグーグルの仕様に合わせてくれた方が、今後が楽ですから。

**Comment by big2men** [comment]
> 別の案としては、このプラグインの互換性が問題なら、旧版の#gmapfunを#gmapfun2に名前を変えて修正版をリリースするのもいいのではないでしょうか。

そうです、「このプラグインの互換性」が問題なんですよ。一度世に出した以上は変えるのは慎重にいかないといけなくなりますので。。

僕ができることは `#gmap` の緯度経度の順番を変えた `#gmap2` を作ることぐらいですかね。。
そして、徐々に `#gmap2` への移行を促していく、という流れになります。

#19 に関してはまた時間のある時に調査してみますね。

**Comment by umihoshi** [comment]
グーグルマップ関係プラグインの問題を再度オープンさせていただきました。
ここに外部の人間が書くことはNGということは十分承知しています。
しかしながらHAIK-teamに以前からこの不具合を不具合報告しても放置されてきた現状では，HAIKユーザーの利益のためには，やむを得ず問題のあることと，解決法が見つかったことをここで報告せざるを得ないと判断いたしました。

（不具合の内容）
Googleマップの仕様変更で支払いの登録とキーが必須となりました。従来キーの設置は「その他のタグ」に書けばエラーを回避できました。しかし，現在はそれでもエラーが解消できなくなり，事実上HAIKのプラグインは使用できなくなりました。HTMLタグを貼り付ける方法ではレスポンシブにならないことと，過去の地図をすべて書き換えなければならないことで根本的解決にはなりません。通常のHAIKの操作で地図を設置してエラーになる時点で，ソフトウエアとしてはアウトです。

わたしが確認した解決法は以下の通り，

gmap.inc.phpnoの106行目，
<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false"></script>
を削除する。
そしてその行に，
<script src="https://maps.googleapis.com/maps/api/js?key=APIキー"></script>
を書く。この結果従来必要だった「その他のタグ」や「フッター」にキーを書くことは不要になり，地図も正常に表示される。

gmapfun.inc.phpは150行目削除し，同様にキーのある記述に入れ替えるとエラーが解消する。ただしマーカーをクリックしたときの動作に問題が残る。

修正案としては，これらプラグインの修正と，HAIKの設定でキーを入力し，それをプラグインに引き渡すようにすれば良いと思われます。
