### ISSUE TITLE
初回のログイン後に，ページ移動するとログインが解除されてしまう

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#31]
7betaになってから気がついた現象です。
　私のはクロームとWindows10の64bit環境ですが，ログインしても他ページへ移動するとログインが解除され，再度ログインしなおさなければならないことが頻発しています。2回目のログイン以降はそういう現象は出ません。
　初回のログインだけの現象のようです。他環境ではどうなのかは不明ですが，何度も再現されるので不具合報告としておきます。

**Comment by umihoshi** [comment]
サイトをhttpsにしたことが関係しているかもしれません。

**Comment by big2men** [comment]
> サイトをhttpsにしたことが関係しているかもしれません。

この可能性はありますね。
http と https では COOKIE が共有されないので。

こちら確認環境がなく、お手数かけますが、
http と https の両方でどんな挙動になるか調べていただけますか。

お手軽に初回ログインを調べる方法も書いておきます。
Chrome でシークレットウィンドウを開けば COOKIE がない状態でアクセスできます。
シークレットウィンドウで試す→閉じる、という方法で初回ログインを何度も試行できます。

**Comment by umihoshi** [comment]
デスクトップPCのWindows10の64bit環境で，PCを起動して，最初のGooglechrome立ち上げで，この現象を確認しました。最初からhttpsでトップページに入り，ログイン，編集のため他ページ移動したらログインが解除。
移動先で再度ログイン。その後はログイン状態が維持。

**Comment by umihoshi** [comment]
別のPCでもやってみました。同じ症状です。シークレットウインドウで実験。
初回にhttpsでログインするとページ移動でログインが解除されます。

**Comment by umihoshi** [comment]
他の人に確認してもらいました。
●QHM 6.04、少し自分でプログラム修正、
ロリポップスタンダードプラン。

テストで使っているロリポップの共用SSLで試してみました。
https://chicappa-isao.ssl-lolipop.jp/haik/

特にログイン、ログアウト関係でおかしな動きはありません。

●HAIK 6.0.7による参考データです。
以下の条件ではSSLでのページ移動でログイン解除はありません。

HAIK 6.0.7
サーバー：XSERVER
PHPVer：6.22
OS：Mac OS 10.11.6
ブラウザ：Safari 10.0.2　FireFox 50.1.0　Google Chrome 55.0.2883.95
Google Chromeのシークレットウインドウでも症状は出ません。

　上の2例と私の環境との違いはPHP7.0.7とhaik7.0.0である点です。試しにPHP5.6＋haik7.0.0にしてみたところ障害は出ませんでした。PHP7に戻したら、再び症状が出ました。どうやらPHP7とhaik7の組み合わせだとダメなようです。

**Comment by Yujiro01** [comment]
httpsでのアクセスをHAIK 7.0.0 b2でテスト。件のトラブル出ません。

サーバー：XSERVER
PHP 7.0.7
HAIK 7.0.0 beta.2

OS：Mac OS 10.11.6
ブラウザ：Safari 10.0.2　FireFox 50.1.0　Google Chrome 55.0.2883.95
Google Chromeのシークレットウインドウでも症状は出ません。

**Comment by umihoshi** [comment]
7.0.0.bet2では今のところ症状が出ていません。
治ったのか？再度症状が出たらオープンにします。

**Comment by umihoshi** [comment]
chromeでクッキーの初期化をすると，ログインが解除されるので，クッキーまわりがSSLで何かうまくいってない印象です。

**Comment by umihoshi** [comment]
逆の現象にも遭遇しました。
ログアウトしたはずなのに，何時間かたったあとで別ページに移動したらログイン状態になりました。
初回トラブルで，複数回ログインした影響かもしれません。
