### ISSUE TITLE
「HTTP/SSL接続」を「SSL接続」に設定してもSSLで表示されない

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#33]
サイトをサーバー設定でSSLにしているのに、HAIKの設定から「サイト情報の設定」ｰ「HTTP/SSL接続」を「SSL接続」にしても、サイトがSSLで表示されません。
　アドレスを明示的にhttpsにしないとダメです。
　CLUB掲示板で同様な現象の報告があり、複数ユーザーで確認されています。

**Comment by big2men** [comment]
「HTTP/SSL接続」はQHMから北研のサーバーへ接続する時の設定ですので、サイトへのSSL接続を強制するものではありません。
（もはや北研サーバーと接続しないのでこの設定は無用の長物です）

現状、QHMではそれをサポートする設定はありません。
特定のページのみSSLを強制するための `#ssl` はありますので、それを利用するか `.htaccess` 等のサーバー設定を利用してSSLへリダイレクトしてください。
