### ISSUE TITLE
HAIK 7.0.0 b2 において#gmap のマップ表示不可

### ISSUE THREAD

**Issue by Yujiro01** [open-qhm/qhm#46]
HAIK 6.0.8 では正常だったものです。

Googleのマップ表示 #gmap が機能しません。

サーバー：XSERVER
PHP　　：7.0.2　と　5.6.22　において同じ症状
HAIK 7.0.0 b2はクリーンインストール

エラー時にはマップが表示されるエリアに以下の文言。

「エラーが発生しました。
このページでは Google マップが正しく読み込まれませんでした。
JavaScript コンソールで技術情報をご確認ください。」

例：
#gmap(zoom=16){{
 奈良県吉野郡下市町長谷１−１
}}

面白いことに、編集状態から復帰する時、一瞬はマップが表示されることがある。

**Comment by umihoshi** [comment]
この症状は過去のコメントでGoogleMapが表示できなかったエラーに似ています。
そのときはGoogleから取得したキーをフッターに書き込んで解決できました。
私の6.0.8アップグレードのサイトでは問題なく表示できていますが，それはフッターにキーを設定しています。
クリーンインストールではキーの設定がされていないので，キーを設定して確認された方がいいと思います。

**Comment by Yujiro01** [comment]
あー、確かにGoogleのAPIキーの問題です。確認しました。
HAIK7.0.0のテストのため、今まで使わず放置していたドメインでMAP表示をしようとしていました。
うっかりミスです。

**Comment by Yujiro01** [comment]
あー、確かにGoogleのAPIキーの問題です。確認しました。
HAIK7.0.0のテストのため、今まで使わず放置していたドメインでMAP表示をしようとしていました。
うっかりミスです。

**Comment by umihoshi** [comment]
それではこのスレッドは解決ということでcloseにしておいた方がいいですね。

**Comment by Yujiro01** [comment]
本件は新しいどメインでGoogleMapを表示するときGoogleのAPIキーの設定が必須ということで
終了です。

close #46

**Comment by Yujiro01** [comment]
umihoshiさん、お手数ですがCloseの具体的な方法を教えていただけないでしょうか。

**Comment by umihoshi** [comment]
スレ主の場合、赤いcommentボタンの左隣にclose issueボタンがあるはずです。それを押せばクローズタブへ移動します。

**Comment by Yujiro01** [comment]
>赤いcommentボタン

ありゃ、これ自体がないですね。

**Comment by Yujiro01** [comment]
umihoshiさんありがとうございます。
本件はGooleが発行するAPIキーをサイトに設定することで解決するはず。
ということです。古いどメインはそれなしでMap表示することもあり。
