### ISSUE TITLE
#qform の「確認画面」の、若干の不備について教えてください。

### ISSUE THREAD

**Issue by nakah** [open-qhm/qhm#50]
以下は以前から気がついていたことですが、報告が遅くなりました。

#qform(,bootstrap,true){{
でメールフォームを作成したときの、若干の不備です。

完成したメールフォームに各項目を記入後、「確認ボタン」を押すと、
「の確認」 という文字が表示されます。
「の」 の前に文字が表示されません。

「送信内容の確認」または、単に「確認」などの表示にするには、
どこを変更すればいいのでしょうか？

現在、サーバーは、エックスサーバーとロリポップです。
PHP 5.6、HAIK v6.0.8 で、テーマは Simpleシリーズの  ikk 一句 と gok 五句 です。
QHM・haik を使いだした２年前から、上記の現象は起きています。

以上、教えていただけると助かります。
お忙しい中、お手数をお掛けします。
よろしく、お願いいたします。

**Comment by big2men** [comment]
@nakah 
```
#qform(問い合わせ,bootstrap,true){{
...
}}
```

フォームのタイトルを上記のように書くと確認画面で「問い合わせの確認」と出ます。
指定しないときに「の確認」になってしまうのは確かに不格好ですね 😓 
また時間を見つけて修正可能か見てみますねー。

それまでは上記の対応でお願いしますm(_ _)m

**Comment by nakah** [comment]
@big2men
早速の、ご回答ありがとうございます。
初歩的な質問で、失礼しました。

もしかすると、私のような方がいるかもしれないので、
フォーラムの方にも書いておきます。
今後とも、よろしく、お願いいたします。

**Comment by big2men** [comment]
いえ、ちょうど見たので回答しました。では、閉じます。
