### ISSUE TITLE
mod_pagespeed 利用時に、写真が縦長にならないようにするには？

### ISSUE THREAD

**Issue by nakah** [open-qhm/qhm#51]
こんにちは。いつも、お世話になります。

私は、エックスサーバーの「mod_pagespeed」（Google製）を
利用して、サイトの表示速度を向上させています。
詳細は下記のURLにあります。

https://goo.gl/BFgWgT

また、写真や画像を、下記などを利用して圧縮しています。

https://tinyjpg.com/

PHP 5.6.22　HAIK v6.0.8（v5.3から同じ現象）
テーマは Simpleシリーズの ikk 一句 と gok 五句 です。

mod_pagespeed を ON にすると、
パソコン（Windows）でも、スマホ（Android）でも、
写真や画像が縦長になってしまいます。

全部が縦長になる訳ではなく、
その時々により、縦長になる写真が違います。

Windows8.1 と 7 で、
ブラウザ（Google Chrome・Internet Explorer） を、

スマホやタブレットくらいの大きさにして確認するとき、
多くの写真が縦長になります。

HAIK で作った私のサイトは下記です。

http://nakahealing.com/

http://nakahealschool.com/

同じエックスサーバーの、同じ環境で使っている、
下記の WordPress 4.7.1（マテリアル2 テーマ）では、

HAIK と同じ写真や画像を使っている投稿もありますが、
縦長になるものは一つもはありません。下記です。

http://nakaheal.com/

上記サイトでは、
ブラウザをスマホやタブレットくらいの大きさにしても、
元の写真の縦横比のまま小さくなります。

HAIK と WordPress は、両方とも、
高速化キャッシュを有効にしています。

また、サイト更新時など、
ときどき キャッシュのクリアを行っています。

HAIKで写真が縦長になるのは、
bootstrap や #cols　が 由来している現象でしょうか？

htmlで記述するときには、例えば、
img src="hoge.jpg" width="304" height="228" border="0"
などとサイズや縦横比を指定できますが、

HAIK では、例えば、
&show(hoge.jpg,,いろは);　の、
どこかに縦横比を記述すれば、縦長にならないでしょうか？

●写真が縦長にならない対策がありましたら、
　教えていただけると助かります。

お忙しい中、いつもいつも、お手数を お掛けします。
よろしく、お願い いたします。

別件ですが、
Medium や Strikingly や teachable なども試行中です。
WordPress も、練習や勉強のために試しています。

しかし、まだ HAIK から離れられる段階ではありません。

私はスクールも行っていて、ネット講座も予定しているので、
永久会員の toiee も少しずつ利用できるようにしたいです。

**Comment by umihoshi** [comment]
nakahさん
　ここはQ＆Aの場では無いと思います。
mod_pagespeedをHAIKで使うときの問題でしたら、それがそもそもHAIKで使えるかどうかも含めて、
　いきなりここでは無く、まずHAIKーCLUBやforumで現象を確認して、HAIKでバグの疑いが濃厚ならここでスレッドを立てるのがいいのではないでしょうか。ここは開発の作業を進める場なので、書き込む内容には良く精査が必要です。

**Comment by nakah** [comment]
@umihoshi

HAIK-CLUB で質問しましたが、削除されました。

HAIK-forum は、批判的・否定的・非コミュニケイティブ・オヤジ的な意見が多く、不快になります。

グーグルは答えてくれません。

HAIK-CLUB に個人的にメールで質問しても、今はサポートだそうです。

ですから、ここで質問しています。
私だけでなく、他にも同じことで困っているひとはいると思います。

いつか HAIK から卒業して、別のシステムに移ります。
それまで、HAIK を、自分のできる形で応援し続けます。

**Comment by umihoshi** [comment]
人格論についてはノーコメントです。
でも、これは単なる「使い方」の質問だと思うのに、なぜCLUBでは削除されるのでしょうね。そのほうにびっくりです。削除されてもしつこく書いてみたらどうなるのかな？
forumの好き嫌いは仕方が無いですが、プログラムに詳しい方が何人かいるので、回答が得やすいと思いますよ。
　ここはサポート窓口では無いので、回答がなくても仕方がないと思っていた方がいいです。

　あとはtomzoさんの「Tips」で質問してみるのも方法です。tomzoさんは検証環境をいくつかお持ちのようですから、確認できるかもしれません。

**Comment by nakah** [comment]
@umihoshi 

HAIK-Team （スペルあってるか？）からのメールでは、
今は初心者の対応に追われていて、初歩的な質問しか受けられないそうです。

削除されてもしつこく書くことも、ご遠慮くださいというふうな回答でした。
今は何とか HAIK-Team の、今のやり方に、ご協力くださいとのことでした。

HAIK-Team には、使い方ではない、
システムやテーマのサポートや開発についての質問もしているので、
それに回答をしてもらうためにも、これ以上、しつこくはできません。

HAIK-forum は、本当なのか分からない意見や、偏狭な意見や、偉ぶったような意見があり、
不快になることもあり嫌なのですが、ここで回答が得られなかったら質問してみます。

ここがサポート窓口でないことは分かっています。
他にないので、仕方なく書いています。ご了承ください。

tomzoさんはフレンドリーな方なので、もし回答が得られなかったら
Tips などで直接聞いてみます。

ありがとうございました (^_^)

**Comment by umihoshi** [comment]
意外にCSSの改造で表示が改善できるかもしれないので、Tipsでネタを振ってみるのはいいかもしれませんよ。
今のforumはCLUB掲示板削除問題で、ちょっと怒り気味なので、とがった発言が目立ちますが、本来は技術系の人が多いので、大いに頼った方がいいです。CLUBが頼りにならないなら、ｆorumをぜひ利用してください。

**Comment by nakah** [comment]
下記に関連する記事がありました (^_^)/

https://github.com/open-qhm/qhm/pull/37

時間を見つけて試してみます。

**Comment by umihoshi** [comment]
#24
 も画像表示のことなので、なんとかならないかな～

**Comment by umihoshi** [comment]
forumでbeeさんが改善方法を考察していますね。

**Comment by nakah** [comment]
http://haikforum.qhmtips.com/patio/patio.cgi?read=87&ukey=0

上記の 2017/01/15(Sun)  21:57 23:02 などにより解決しました。

それより、何より、GitHub Issues で、このような質問をしてしまい、
お騒がせいたしました m(_ _)m
