### ISSUE TITLE
HAIK　7.0 beta3とPHP7で編集画面に入れない

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#53]
ver.7 beta3版にアップデートするとPHP7で編集画面に入れない。
以下のエラー。
Parse error: syntax error, unexpected 'new' (T_NEW) in /home/***/**********.com/public_html/plugin/attach.inc.php on line 68

PHP5.6では正常。

beta3に入っているattach.inc.phpの更新忘れではないかと思います。

**Comment by tanakakc** [comment]
@umihoshi 

ご報告ありがとうございます！
update版のzipファイルを修正しましたので、お試しください。

お手数をおかけします。

**Comment by umihoshi** [comment]
この修正の結果です。
ロリポップのライト版でのPHP7beta3にアップデートで問題なかったそうです。
CGIのPHP７．１です。
