### ISSUE TITLE
#search と#search2がエックスサーバーPHP7.1.4で機能しない

### ISSUE THREAD

**Issue by umihoshi** [open-qhm/qhm#68]
表題の通りですが，
エックスサーバーでは最新環境PHP7.1.4では検索結果がまったく表示されません。

現在確認できたのは，
HAIK7.0.2で，
(1)エックスサーバーではPHP7.0.18に落とすと動作する。
(2)さくらサーバーではPHP7.1.4でも検索は問題なし。

となっています。
　かなり微妙なところで障害が出ています。今後のPH環境のことを考えると，修正が必要だと思います。

**Comment by big2men** [comment]
@umihoshi 情報提供ありがとうございます。
調査により原因が分かりました。

問題となっている箇所は [ここ](https://github.com/open-qhm/qhm/blob/master/plugin/search.inc.php#L144)と[ここ](https://github.com/open-qhm/qhm/blob/master/plugin/search2.inc.php#L203)の `mb_ereg_replace` 関数でした。

`mb_ereg_replace` は `mb_regex_encoding` 関数の値をもとにエンコーディングを判別して置換処理を行いますが、渡す文字列とそのエンコーディングにミスマッチがあると正常に処理ができず `NULL` を返します。
これを防ぐには渡す文字列とそのエンコーディングを合わせる必要があります。

HAIK では通常 `UTF-8` エンコーディングを使用しますが、 `mb_regex_encoding` のケアが不十分だったことがエックスサーバーでミスマッチが発生する原因でした。
エックスサーバーは php.ini に設定されている `mbstring.internal_encoding` がデフォルトで `EUC-JP` になっているため、初期化処理で `mb_internal_encoding("UTF-8")` と明示しても、 `mb_regex_encoding("UTF-8")` とは明示していなかったため、 `mb_regex_encoding = EUC-JP` になってしまい、上述のミスマッチが発生したようです。

こちらについては初期化処理を改良することで防げそうですので、修正版を本日中にでもリリースいたします。

**Comment by big2men** [comment]
PHP7.0 で問題がなく、 PHP7.1 で問題となった原因はリリースノートにも無いようで簡単には分からないですが、 `mb_regex_encoding` に関する修正は合ったようなので内部エンコーディングの扱いに変化があったのではと推察できます。
