### ISSUE TITLE
QBlog のメニューバー編集からのプレビューがおかしい

### ISSUE THREAD

**Issue by big2men** [open-qhm/qhm#74]
QBlog のメニューバーが表示されない画面でプレビューされるので全く参考にならない

**Comment by umihoshi** [comment]
テストしました。ひとつどうかなと思える動作がありました。
これは仕方が無いのかもれませんが，報告はしておきます。
私のサイトでmenu2と名付けたページを特定ページでメニューに使っています。
そのような独自メニューではプレビューがメニュー領域になりませんでした。
一般ページ扱いなのでしょう。「メニューとしてプレビュー」も選択できればいいのかもしれません。

**Comment by big2men** [comment]
@umihoshi ありがとうございます！

> 私のサイトでmenu2と名付けたページを特定ページで独自メニューに使っています。
そのような独自メニューではプレビューがメニュー領域になりませんでした。
たぶん一般ページ扱いなのでしょう。これは仕様上は仕方の無いことかもしれません。

そうですね、仰る通り一般ページ扱いです。
メニューやナビは特別扱いしているので一般ページをメニューとしてのプレビューはできません。
もしできるとしてもそれをUIとして追加することは多分無いでしょう。

私としては、一部のページでのみ使うメニューなら影響は少ないので、どんどん更新して動作確認するので問題無いのでは、と思います。
一応、ページとしてプレビューはできるので致命的なミスは起こりにくいはずです。

そうは言っても影響範囲大きいんだよーって人のために、代替案もあります。

## 隠しページとして複製し、動作確認する

まず、テスト用の隠しページ `:MenuTest` を作ります。
次にカスタムメニューを複製します。 `:menu2` とか。

**`:MenuTest`**
```
#menu(:menu2)
```

**`:menu2`**
```
* 見出し
** [[ページ名]]
〜〜
```

隠しページと隠しページの組み合わせなので、好きなだけ動作確認ができます。
満足の行く出来になったら `menu2` に `:menu2` の内容をコピペするだけです。

## 無理やりプレビューしてみる

思いついて試してみましたが、こんな風に書けば無理やりプレビューはできました。
上記より楽な方法です。

`menu2` ページにこう追記します。
```
#eyecatch{{
#menu(menu2)
}}
```

アイキャッチ部分にエラーメッセージが出ますが、
メニューの部分は問題無くプレビューできます。（オレンジ色の枠はでません）
最後に保存する際に上の3行を消すかコメントアウトすれば問題無いです。

**Comment by umihoshi** [comment]
「むりやり」のほうでやってみました。普段はコメントアウトしておいて，プレビューしたい時だけ使うというのが簡単でいいですね。
