### ISSUE TITLE
ブログアーカイブ年別表示を見やすくする

### ISSUE THREAD

**Issue by big2men** [open-qhm/qhm#77]
Ref https://github.com/open-qhm/qhm/pull/76#issuecomment-319842162

- 年数をクリックして開いたところには年数はいらないんじゃないか
- インデントしたら見やすいんじゃないか

**Comment by umihoshi** [comment]
年と月のフォントが同じで見分けにくいですね。月の行を一字下げてくれると見やすくなるのに。なんとかならないですかね。

**Comment by big2men** [comment]
フォントは変えないと思いますが、↑の説明の通り、字下げ（インデント）と年数の省略をもくろんでます。

**Comment by umihoshi** [comment]
それは楽しみです。よろしくお願いします。

**Comment by umihoshi** [comment]
CSSで月の字下げができました。
ここであまり書くのは良くないとは思っていますが，右に出る>などのやじるしのセレクタ名がどうしてもわかりませんでした。教えていただけないでしょうか。

**Comment by umihoshi** [comment]
現行のままでCSSを使って月の字下げは実現できました。
