### ISSUE TITLE
QBlogのリスト表示でサムネイル画像が歪む

### ISSUE THREAD

**Issue by big2men** [open-qhm/qhm#87]
## What

- QBlog の記事一覧に表示されるサムネイル画像が元画像の縦横比によっては歪んで見えてしまう問題を修正する
- 縦横比を維持したまま中央付近をクロップするのが良さそう

## Why

気になる

## How

画像を img ではなく背景画像として cover 指定するか、CSSの  `object-fit` プロパティを使うかする。
object-fit は IE で全く対応していないので背景画像が妥当。

**Comment by umihoshi** [comment]
すみません。普段ここに書かないようにしてますが，7.1.6を適用したら，サムネイル画像が表示されなくなりました。該当サイトはhttps://umihoshi.comのQblogです。

**Comment by umihoshi** [comment]
グリッドだとサムネイルが表示できました。リストでは表示できません。
とりあえずグリッドでしのぎます。

**Comment by big2men** [comment]
@umihoshi 
なんと！ご報告ありがとうございます。
手元の環境では haik_seed でのリスト表示に問題はありませんでした。

今回の変更により、画像の表示を JavaScript で行うようにしましたが、 JavaScript の実行中にエラーが発生しているかも知れません。
よろしければ、下記の手順でエラーを報告していただけますか。

1.  サイトを開いてリスト表示に変えておく
2. JavaScript コンソールを開く（Chrome なら「表示」＞「開発／管理」＞ JavaScript コンソール）
3. ブログページを開く
4. コンソールにエラーが表示されたらコピー
5. 当ISSUEのコメントにペーストして投稿
6. グリッド表示に戻す

**Comment by umihoshi** [comment]
職場の別のPCで、指示されたエラーをチェックしようとしたところ、リスト表示正常でした。
更新から時間をおいているので、キャッシュか何かの影響だったのでしょうか。
今夜自宅に帰ったら、うまくいかなかったPCで再度確認してみます。

**Comment by umihoshi** [comment]
報告です。
アップデート直後にブラウザキャッシュのクリアが必要だと判明しました。
7.1.6には問題はありませんでした。

**Comment by big2men** [comment]
なるほど。そう言われたらそうですね。
ありがとうございました！ HAIK-TEAMにも報告しておきます。
