### ISSUE TITLE
印刷用CSSを見直す

### ISSUE THREAD

**Issue by big2men** [open-qhm/qhm#88]
## What

- Haik に同梱している Bootstrap CSS には Bootstrap 生成の印刷用CSSが含まれている
- これがくせもので、見たまま印刷、というわけにはいかない
- 印刷用CSSを完全に無くすか、調整するなどして落とし所を探る

## How

印刷するとアレッとなるから

## How

同梱しているBootstrap CSSから印刷用の指定を全て排除する。
or
印刷用の指定を調整してマシにする。

**Comment by Yujiro01** [comment]
v7.2においてHAIKのデザインによってはブラウザ表示にデザイン崩れあり。
参考ページ
http://aampy.com/index.php
上のURLにアクセスし、メニューの中の「テスト」をクリック。
メニュー中、「-」を使ったリンクの記述ではバックグランドが青になる。
（これは元デザインではありません）
少なくとも　Cool、Bio、 Flat の各デザインで発生。

**Comment by Yujiro01** [comment]
v7.2においてHAIKのデザインによってはブラウザ表示にデザイン崩れあり。
参考ページ
http://aampy.com/index.php
上のURLにアクセスし、メニューの中の「テスト」をクリック。
メニュー中、「-」を使ったリンクの記述ではバックグランドが青になる。
（これはv7.1.7以前には起こりません）
少なくとも　Cool、Bio、 Flat の各デザインで発生。

更に、印刷ではアイキャッチ部の画像が表示されず、ナビ部のリンク表示もおかしい。
（Mac版 Safari 、Firefox 、Chrome の三つのブラウザで確認）
