### ISSUE TITLE
FontAwesome 5 に対応

### ISSUE THREAD

**Issue by big2men** [open-qhm/qhm#96]
## WHAT
- iconプラグインを FontAwesome 5 に対応させる
- まずは FontAwesome 4 の書き方のままでも自然に5系のアイコンが表示されるところを目指す
- [新機能][fa5-implements]への対応は TODO
- 5 で追加されたアイコンについては `&icon(fab,line);` のように、アイコンセットの指定を `fa` ではなく、 `fab` や `fas` 等で書くことになる

## WHY
新しいSVGアイコンが使いたい

## HOW

CDNの読み込み先を変更する。
ただし、5より JavaScript に変更されていること、アイコン名やクラス定義が変更されていることを注意する。
今回はFontAwesome より配布されている `v4-shims.js` を利用する。

[fa5-implements]: https://fontawesome.com/how-to-use/svg-with-js

**Comment by umihoshi** [comment]
7.2.0使ってみました。エックスサーバーのPHPを7.2にアップしても不具合は無いようですが，ブラウザキャッシュをクリアしないと，アイコンがずれる，スクロールアップの矢印が動かないという現象が出ました。HAIK設定のキャッシュを削除しても直りませんでしたが，Google Chromeの画像キャッシュを削除したところ正常になりました。アップデート直後はブラウザのキャッシュをクリアするという一般的注意喚起は必要でしょうね。
